"""
PDF Generator Templates
=======================
Advanced, template-based PDF generation engine.
Provides reusable structures for:
1. Notepad Reports
2. To Do Lists
3. Payments & Billings History
"""

import os
import re
from typing import Optional
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
import matplotlib
matplotlib.use("Agg")  # Non-interactive backend
import matplotlib.pyplot as plt
import io

from app.utils.pdf_generator import NumberedCanvas, THEMES, get_numbered_canvas
import logging

logger = logging.getLogger(__name__)


def _format_date_label(dt) -> str:
    if not dt or dt == "-":
        return "-"
    from datetime import datetime, date
    if isinstance(dt, (datetime, date)):
        return f"{dt.day} {dt.strftime('%B %Y')}"
    try:
        clean_date_str = str(dt).replace("T", " ").split(" ")[0]
        parsed_dt = datetime.strptime(clean_date_str, "%Y-%m-%d")
        return f"{parsed_dt.day} {parsed_dt.strftime('%B %Y')}"
    except Exception:
        return str(dt).replace("T", " ").split(" ")[0]


class BasePDFReport:
    """Base class for all PDF reports providing common styling and helpers."""
    def __init__(self, filename: str, config: dict = None):
        self.filename = filename
        self.config = config or {}
        self.theme_name = self.config.get("theme", "navy").lower()
        if self.theme_name not in THEMES:
            self.theme_name = "navy"
        self.theme = THEMES[self.theme_name]
        
        self.title_text = self.config.get("title") or "Report"
        self.subtitle_text = self.config.get("subtitle") or "Generated by Vixx Personal Assistant"
        
        self.doc = SimpleDocTemplate(
            filename,
            pagesize=letter,
            leftMargin=36,
            rightMargin=36,
            topMargin=45,
            bottomMargin=54
        )
        
        self.styles = getSampleStyleSheet()
        self._init_styles()
        self.story = []

    def _init_styles(self):
        self.title_style = ParagraphStyle(
            'DocTitle',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=24,
            leading=28,
            textColor=self.theme["primary"]
        )
        self.subtitle_style = ParagraphStyle(
            'DocSubtitle',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#64748b")
        )
        self.section_heading = ParagraphStyle(
            'SectionHeading',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=self.theme["primary"]
        )
        self.subsection_heading = ParagraphStyle(
            'SubsectionHeading',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=11,
            leading=14,
            textColor=self.theme["secondary"]
        )
        self.metric_label_style = ParagraphStyle(
            'MetricLabel',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#64748b"),
            alignment=1
        )
        self.metric_val_style = ParagraphStyle(
            'MetricValue',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=13,
            leading=16,
            textColor=self.theme["primary"],
            alignment=1
        )
        self.table_hdr_style = ParagraphStyle(
            'TableHdr',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=9,
            leading=11,
            textColor=self.theme["white"]
        )
        self.table_cell_style = ParagraphStyle(
            'TableCell',
            parent=self.styles['Normal'],
            fontName='Helvetica',
            fontSize=8.5,
            leading=11,
            textColor=self.theme["text"]
        )
        self.table_cell_bold = ParagraphStyle(
            'TableCellBold',
            parent=self.styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8.5,
            leading=11,
            textColor=self.theme["text"]
        )
        self.empty_style = ParagraphStyle(
            'EmptyStyle',
            parent=self.styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#94a3b8"),
            alignment=1
        )

    def add_header(self):
        self.story.append(Paragraph(self.title_text, self.title_style))
        self.story.append(Spacer(1, 4))
        self.story.append(Paragraph(self.subtitle_text, self.subtitle_style))
        self.story.append(Spacer(1, 15))

    def add_metrics_table(self, metrics: list):
        """metrics: list of tuples (Label, Value)"""
        if not metrics:
            return
        col_width = 540 / len(metrics)
        col_widths = [col_width] * len(metrics)
        
        metric_data = [
            [Paragraph(m[0], self.metric_label_style) for m in metrics],
            [Paragraph(m[1], self.metric_val_style) for m in metrics]
        ]
        
        metrics_table = Table(metric_data, colWidths=col_widths)
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), self.theme["accent"]),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('INNERGRID', (0,0), (-1,-1), 1.5, self.theme["white"]),
            ('BOX', (0,0), (-1,-1), 1.5, self.theme["white"]),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ]))
        self.story.append(metrics_table)
        self.story.append(Spacer(1, 15))

    def add_empty_state(self, message: str = "No data available matching the criteria."):
        self.story.append(Spacer(1, 10))
        self.story.append(Paragraph(message, self.empty_style))
        self.story.append(Spacer(1, 10))

    def build_chart(self, plot_func) -> Optional[Image]:
        """Runs a plotting function and returns a ReportLab Image object of the chart."""
        try:
            fig, ax = plt.subplots(figsize=(6, 2.5), dpi=300)
            plot_func(fig, ax)
            fig.tight_layout()
            
            img_buf = io.BytesIO()
            fig.savefig(img_buf, format='png', bbox_inches='tight')
            img_buf.seek(0)
            plt.close(fig)
            
            return Image(img_buf, width=360, height=150)
        except Exception as e:
            logger.error(f"Error building chart: {str(e)}")
            return None

    def build(self):
        os.makedirs(os.path.dirname(self.filename), exist_ok=True)
        canvas_maker_cls = get_numbered_canvas(self.theme_name)
        print(f"DEBUG: BasePDFReport.build() canvasmaker is {canvas_maker_cls}")
        self.doc.build(self.story, canvasmaker=canvas_maker_cls)
        return self.filename


class NotepadReport(BasePDFReport):
    """Formats and prints the Notepad contents for a project in full detail."""
    def generate(self, content: str):
        self.add_header()
        
        self.story.append(Paragraph("Notepad Notes", self.section_heading))
        self.story.append(Spacer(1, 10))
        
        if not content or not content.strip():
            self.add_empty_state("No notepad content found for this project.")
            self.build()
            return
            
        paragraphs = content.split("\n")
        for p in paragraphs:
            p_strip = p.strip()
            if not p_strip:
                self.story.append(Spacer(1, 6))
                continue
                
            if p_strip.startswith("###"):
                title = p_strip.replace("###", "").strip()
                self.story.append(Paragraph(title, self.subsection_heading))
                self.story.append(Spacer(1, 4))
            elif p_strip.startswith("##"):
                title = p_strip.replace("##", "").strip()
                self.story.append(Paragraph(title, self.subsection_heading))
                self.story.append(Spacer(1, 4))
            elif p_strip.startswith("#"):
                title = p_strip.replace("#", "").strip()
                self.story.append(Paragraph(title, self.section_heading))
                self.story.append(Spacer(1, 6))
            elif p_strip.startswith("- ") or p_strip.startswith("* "):
                item_txt = p_strip[2:].strip()
                bullet_style = ParagraphStyle(
                    'BulletStyle',
                    parent=self.styles['Normal'],
                    fontName='Helvetica',
                    fontSize=9.5,
                    leading=13,
                    leftIndent=15,
                    firstLineIndent=-10,
                    textColor=self.theme["text"]
                )
                self.story.append(Paragraph(f"&bull; {item_txt}", bullet_style))
                self.story.append(Spacer(1, 4))
            else:
                body_style = ParagraphStyle(
                    'BodyStyle',
                    parent=self.styles['Normal'],
                    fontName='Helvetica',
                    fontSize=9.5,
                    leading=14,
                    textColor=self.theme["text"]
                )
                formatted = p_strip
                formatted = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', formatted)
                self.story.append(Paragraph(formatted, body_style))
                self.story.append(Spacer(1, 6))
                
        self.build()


class ToDoReport(BasePDFReport):
    """Detailed To Do List Report showing tasks, statuses, priorities, and description notes."""
    def generate(self, tasks: list):
        self.add_header()
        
        completed_tasks = sum(1 for t in tasks if str(t.get("status")).lower() in ["done", "completed"])
        total_tasks = len(tasks)
        pending_tasks = total_tasks - completed_tasks
        pct = f"{int((completed_tasks/total_tasks)*100)}%" if total_tasks > 0 else "0%"
        
        self.add_metrics_table([
            ("TOTAL TASKS", str(total_tasks)),
            ("COMPLETED TASKS", f"{completed_tasks} ({pct})"),
            ("PENDING TASKS", str(pending_tasks))
        ])
        
        self.story.append(Paragraph("Tasks Backlog List", self.section_heading))
        self.story.append(Spacer(1, 8))
        
        if tasks:
            headers = ["Project", "Task Details & Description", "Priority / Status", "Hours (Est/Act)", "Due Date"]
            widths = [100, 180, 100, 80, 80]
            table_data = [[Paragraph(h, self.table_hdr_style) for h in headers]]
            
            for t in tasks:
                proj = t.get("project_title") or "General"
                title = t.get("title") or "Untitled"
                desc = t.get("description") or ""
                prio = str(t.get("priority") or "medium").upper()
                status = str(t.get("status") or "todo").upper()
                est = f"{t.get('estimated_hours') or 0:.1f}h"
                act = f"{t.get('actual_hours') or 0:.1f}h"
                dt = t.get("due_date") or "-"
                
                details_text = f"<b>{title}</b>"
                if desc:
                    details_text += f"<br/><font color='#64748b' size='7'>{desc}</font>"
                    
                row = [
                    Paragraph(proj, self.table_cell_bold),
                    Paragraph(details_text, self.table_cell_style),
                    Paragraph(f"{prio} / {status}", self.table_cell_style),
                    Paragraph(f"{est} / {act}", self.table_cell_style),
                    Paragraph(_format_date_label(dt), self.table_cell_style)
                ]
                table_data.append(row)
                
            tbl = Table(table_data, colWidths=widths)
            tbl.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), self.theme["primary"]),
                ('INNERGRID', (0,0), (-1,-1), 0.5, self.theme["border"]),
                ('BOX', (0,0), (-1,-1), 0.5, self.theme["primary"]),
                ('BOTTOMPADDING', (0,0), (-1,-1), 5),
                ('TOPPADDING', (0,0), (-1,-1), 5),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ]))
            self.story.append(tbl)
        else:
            self.add_empty_state("No tasks recorded matching the selection criteria.")
            
        self.build()


class PaymentsReport(BasePDFReport):
    """Detailed Payments and Billings Report showing transaction history, amounts, statuses, and notes."""
    def generate(self, payments: list):
        self.add_header()
        
        received_amt = sum(float(p.get("amount") or 0) for p in payments if str(p.get("status")).lower() == "received")
        currency = payments[0].get("currency", "INR") if payments else "INR"
        
        proj_total = self.config.get("project_total_amount") or 0.0
        if proj_total > 0:
            remaining_amt = proj_total - received_amt
        else:
            remaining_amt = sum(float(p.get("amount") or 0) for p in payments if str(p.get("status")).lower() != "received")
            
        self.add_metrics_table([
            ("TOTAL TRANSACTIONS", str(len(payments))),
            ("RECEIVED INCOME", f"{received_amt:,.0f} {currency}"),
            ("REMAINING PAYMENT", f"{remaining_amt:,.0f} {currency}")
        ])
        
        self.story.append(Paragraph("Financial Ledger & Payment History", self.section_heading))
        self.story.append(Spacer(1, 8))
        
        if payments:
            headers = ["Project", "Payment Type & Notes", "Amount", "Received / Due Date", "Status"]
            widths = [110, 170, 90, 100, 70]
            table_data = [[Paragraph(h, self.table_hdr_style) for h in headers]]
            
            for p in payments:
                proj = p.get("project_title") or "General"
                pay_type = str(p.get("payment_type") or "Installment").upper()
                notes = p.get("notes") or ""
                amt = float(p.get("amount") or 0)
                curr = p.get("currency") or "INR"
                status = str(p.get("status") or "pending").upper()
                
                if status == "RECEIVED":
                    dt = p.get("received_date") or "-"
                else:
                    dt = p.get("due_date") or "-"
                
                details_text = f"<b>{pay_type}</b>"
                if notes:
                    details_text += f"<br/><font color='#64748b' size='7'>{notes}</font>"
                    
                row = [
                    Paragraph(proj, self.table_cell_bold),
                    Paragraph(details_text, self.table_cell_style),
                    Paragraph(f"<b>{amt:,.0f} {curr}</b>", self.table_cell_style),
                    Paragraph(_format_date_label(dt), self.table_cell_style),
                    Paragraph(status, self.table_cell_style)
                ]
                table_data.append(row)
                
            tbl = Table(table_data, colWidths=widths)
            tbl.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), self.theme["primary"]),
                ('INNERGRID', (0,0), (-1,-1), 0.5, self.theme["border"]),
                ('BOX', (0,0), (-1,-1), 0.5, self.theme["primary"]),
                ('BOTTOMPADDING', (0,0), (-1,-1), 5),
                ('TOPPADDING', (0,0), (-1,-1), 5),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ]))
            self.story.append(tbl)
        else:
            self.add_empty_state("No payment transaction records found matching the selection criteria.")
            
        self.build()
